name: Add Reviewer on Issue

on:
  issues:
    types: [opened]

jobs:
  add_reviewer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
      
    - name: Add new reviewer if not exists
      env:
        ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
      run: |
        reviewers_file="reviewers.txt"
        author="$ISSUE_AUTHOR"
        if ! grep -Fxq "$author" $reviewers_file
        then
          echo "$author" >> $reviewers_file
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add $reviewers_file
          git commit -m "Add new reviewer: $author"
          git push
          echo "Added $author to $reviewers_file"
        else
          echo "$author already in reviewers.txt"
        fi
